config/routes.rb
Rails.application.routes.draw do
  root 'budgets#new', as: :budgets_new
  post '/', to: 'budgets#create', as: :budgets_create
  get '/:id', to: 'budgets#show', as: :budget
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  before_save :calculate_tax

  def calculate_tax
    if self.days_until_due_date % 10 === 0
      percent_tax = 0.0165 * (self.days_until_due_date / 10)
    else
      percent_tax = 0.0165 * ((self.days_until_due_date / 10) + 1)
    end
    self.tax_value = self.duplicate_value * percent_tax
    self.value_to_pay = self.duplicate_value - self.tax_value
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :requester_email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :company_name, presence: true
  validates :monthly_revenue, presence: true
  validates :duplicate_value, presence: true
  validates :duplicate_value, :numericality => { :greater_than_or_equal_to => 500 }
  validates :days_until_due_date, presence: true
  validates :days_until_due_date, :numericality => { :greater_than_or_equal_to => 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  def index
  end

  def new
    @budget = Budget.new
  end

  def show
    @budget = Budget.find(params[:id])
  end

  def create
    @budget = Budget.new(budget_params)
    if @budget.save
      redirect_to @budget
    else
      render "new"
    end
  end

  private

    def budget_params
      params.require(:budget).permit(:requester_name, :requester_email,
                                     :company_name, :monthly_revenue,
                                     :duplicate_value, :days_until_due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="text-center">Faça uma simulação para seu título</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <p>Campos obrigatórios marcados com *
    <%= form_for @budget, :html => {:class => 'form'}, url: {action: "create"} do |f| %>
      <%= render 'shared/error_messages' %>

      <div class="form-group">
        <%= f.label :requester_name, "Nome do Solicitante" %>
        <%= f.text_field :requester_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :requester_email,  "Email do Solicitante *" %>
        <%= f.email_field :requester_email, class: "form-control", :required => true %>
      </div>

      <div class="form-group">
        <%= f.label :company_name, "Nome da Empresa *" %>
        <%= f.text_field :company_name, class: "form-control", :required => true %>
      </div>

      <div class="form-group">
        <%= f.label :monthly_revenue, "Faturamento Mensal (R$) *" %>
        <%= f.number_field :monthly_revenue, class: "form-control", :required => true %>
      </div>

      <div class="form-group">
        <%= f.label :duplicate_value, "Valor do Título (Valor Mínimo de R$ 500,00) *" %>
        <%= f.number_field :duplicate_value, class: "form-control", :required => true %>
      </div>

      <div class="form-group">
        <%= f.label :days_until_due_date, "Dias até o vencimento (no mínimo 10) *" %>
        <%= f.number_field :days_until_due_date, class: "form-control", :required => true %>
      </div>

      <div class="form-group">
        <%= f.submit "Submeter", class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/budgets/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Simulação para <%= @budget.company_name %></h1>
    <div class="jumbotron">
      <p><strong>Nome do Solicitante: </strong><%= @budget.requester_name %></p>
      <p><strong>Email do Solicitante: </strong><%= @budget.requester_email %></p>
      <p><strong>Nome da Empresa: </strong><%= @budget.company_name %></p>
      <p><strong>Faturamento Mensal: </strong><%= number_to_currency(@budget.monthly_revenue, :unit => "R$") %></p>
      <p><strong>Valor do Título: </strong><%= number_to_currency(@budget.duplicate_value, :unit => "R$") %></p>
      <p><strong>Dias até o vencimento: </strong><%= @budget.days_until_due_date %></p>
    </div>
    <div class="jumbotron">
      <p><strong>Valor da Taxa: </strong><%= number_to_currency(@budget.tax_value, :unit => "R$") %></p>
      <p><strong>Valor a Receber: </strong><%= number_to_currency(@budget.value_to_pay, :unit => "R$") %></p>
    </div>

    <%= link_to "Fazer Nova Simulação", budgets_new_url, class: "btn btn-default btn-block" %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FactoringOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @budget.errors.any? %>
  <div class="alert alert-danger">
    <% @budget.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>